version: '3'

services:
  web:
    build:
      context: .
      dockerfile: provision/application/django/Dockerfile
    container_name: test_django
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app